// <auto-generated />
using ITI_Final_Project.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITI_Final_Project.Migrations
{
    [DbContext(typeof(E_CommerceContext))]
    [Migration("20240907043559_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITI_Final_Project.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Phones"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fruits"
                        });
                });

            modelBuilder.Entity("ITI_Final_Project.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Price = 2234m,
                            Quantity = 2,
                            Title = "IPhone 12"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Price = 2234m,
                            Quantity = 2,
                            Title = "Lenovo Legion2"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Price = 3234m,
                            Quantity = 2,
                            Title = "Samsung galaxy 123"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Price = 4234m,
                            Quantity = 2,
                            Title = "Huawei y4"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Price = 5234m,
                            Quantity = 2,
                            Title = "HP victus21"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Price = 6234m,
                            Quantity = 2,
                            Title = "Oppo v13"
                        });
                });

            modelBuilder.Entity("ITI_Final_Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "email@mail.com",
                            FName = "Ramy",
                            LName = "Mai",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            Email = "email@mail.com",
                            FName = "Mai",
                            LName = "Ali",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 3,
                            Email = "email@mail.com",
                            FName = "Ali",
                            LName = "Ramy",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 4,
                            Email = "email@mail.com",
                            FName = "Omar",
                            LName = "Ramy",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 5,
                            Email = "email@mail.com",
                            FName = "Mostafa",
                            LName = "Omar",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 6,
                            Email = "email@mail.com",
                            FName = "Ahmed",
                            LName = "Mostafa",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 7,
                            Email = "email@mail.com",
                            FName = "Sara",
                            LName = "Ahmed",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 8,
                            Email = "email@mail.com",
                            FName = "Osama",
                            LName = "Mohamed",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 9,
                            Email = "email@mail.com",
                            FName = "Mohamed",
                            LName = "Osama",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 10,
                            Email = "email@mail.com",
                            FName = "Nour",
                            LName = "Nour",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 11,
                            Email = "email@mail.com",
                            FName = "Mohamed",
                            LName = "Nour",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 12,
                            Email = "email@mail.com",
                            FName = "Nour",
                            LName = "Ramy",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("ITI_Final_Project.Models.Product", b =>
                {
                    b.HasOne("ITI_Final_Project.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ITI_Final_Project.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
